# Generated by Django 5.2 on 2025-06-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_gmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='total_possible_marks',
            field=models.FloatField(default=0),
        ),
    ]
