# Generated by Django 5.2 on 2025-06-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_gmt', '0003_assignment_assignmentquestion_assignmentresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='assignmentresult',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='studentassignmentsubmission',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='studentassignmentsubmission',
            name='is_graded',
        ),
        migrations.RemoveField(
            model_name='studentassignmentsubmission',
            name='marks_obtained',
        ),
        migrations.AddField(
            model_name='assignmentresult',
            name='total_possible_marks',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='AssignmentQuestion',
        ),
    ]
