# Generated by Django 5.1.7 on 2025-07-30 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0010_alter_coursefeedback_content_quality_rating_and_more'),
        ('trainer_gmt', '0004_remove_assignment_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_gmt.coursetable'),
        ),
    ]
