# Generated by Django 5.2.4 on 2025-08-21 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0032_remove_trainerdata_bank_name_branch_and_more'),
        ('trainer_gmt', '0005_assignment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.JSONField()),
                ('why_interested', models.TextField()),
                ('availability', models.JSONField()),
                ('uploaded_docs', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup_gmt.trainerdata')),
            ],
        ),
    ]
