# Generated by Django 5.2.4 on 2025-08-22 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0032_remove_trainerdata_bank_name_branch_and_more'),
        ('trainer_gmt', '0007_counselor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('preferred_times', models.JSONField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='counseling_resumes/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer_gmt.counselor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup_gmt.studentinformation')),
            ],
        ),
    ]
