# Generated by Django 5.2.4 on 2025-08-22 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0032_remove_trainerdata_bank_name_branch_and_more'),
        ('trainer_gmt', '0009_counselingrequest_google_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup_gmt.logindetails'),
        ),
    ]
