# Generated by Django 5.2.4 on 2025-08-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_gmt', '0010_alter_counselor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselingrequest',
            name='google_calendar_event_id',
        ),
        migrations.AddField(
            model_name='counselingrequest',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
