# Generated by Django 5.2.4 on 2025-08-25 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0032_remove_trainerdata_bank_name_branch_and_more'),
        ('trainer_gmt', '0011_remove_counselingrequest_google_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_domains', models.JSONField(default=list)),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup_gmt.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.JSONField(default=list)),
                ('why_interested', models.TextField()),
                ('availability', models.JSONField()),
                ('docs', models.FileField(blank=True, null=True, upload_to='interviewer_docs/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup_gmt.trainerdata')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('preferred_times', models.JSONField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='interview_resumes/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('session_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meet_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer_gmt.interviewer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup_gmt.studentinformation')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer_gmt.interviewrequest')),
            ],
        ),
    ]
