# Generated by Django 5.2.4 on 2025-09-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_gmt', '0012_interviewer_interviewerapplication_interviewrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewerapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Rejected', 'rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Assigned', 'assigned'), ('Accepted', 'accepted'), ('Rejected', 'rejected'), ('Completed', 'completed'), ('Cancelled', 'cancelled')], default='Pending', max_length=20),
        ),
    ]
