# Generated by Django 5.2.4 on 2025-09-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_gmt', '0013_alter_interviewerapplication_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewrequest',
            name='student',
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='student_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewerapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewerapplication',
            name='why_interested',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
