# Generated by Django 5.2 on 2025-06-05 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup_gmt', '0029_alter_studentinformation_account_holder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='admin/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signup_gmt.logindetails')),
            ],
        ),
    ]
