# Generated by Django 5.2 on 2025-06-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_gmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='role',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
