# Generated by Django 5.2 on 2025-05-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=255)),
                ('course_author', models.CharField(max_length=255)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_image', models.CharField(max_length=500)),
                ('course_video', models.CharField(max_length=500)),
                ('course_description', models.TextField()),
                ('course_rating', models.FloatField()),
                ('about_course', models.TextField()),
                ('total_students_enrolled', models.IntegerField()),
                ('course_specification', models.TextField()),
                ('preknowledge', models.TextField(default=True)),
                ('why_this_course', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_gmt.coursetable')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_gmt.section')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_gmt.lecture')),
            ],
        ),
    ]
