# Generated by Django 5.2 on 2025-05-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0001_initial'),
        ('signup_gmt', '0007_alter_trainerdata_educational_certificates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetable',
            name='course_author',
        ),
        migrations.AddField(
            model_name='coursetable',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup_gmt.trainerdata'),
        ),
    ]
