# Generated by Django 5.2 on 2025-05-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0002_remove_coursetable_course_author_coursetable_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
