# Generated by Django 5.2 on 2025-05-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0003_lecture_video_file_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetable',
            name='course_video',
        ),
        migrations.AddField(
            model_name='coursetable',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='coursetable',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
