# Generated by Django 5.2 on 2025-05-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0004_remove_coursetable_course_video_coursetable_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetable',
            name='total_students_enrolled',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
