# Generated by Django 5.2 on 2025-05-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0005_alter_coursetable_total_students_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.DurationField(),
        ),
    ]
