# Generated by Django 5.1.7 on 2025-06-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0006_alter_lecture_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='course_pdf/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='ppt',
            field=models.FileField(blank=True, null=True, upload_to='course_ppt/'),
        ),
    ]
