# Generated by Django 5.1.7 on 2025-07-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0007_lecture_pdf_lecture_ppt'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetable',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursetable',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
