# Generated by Django 5.1.7 on 2025-07-22 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0008_coursetable_author_name_coursetable_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.FloatField()),
                ('content_quality_rating', models.FloatField()),
                ('trainer_rating', models.FloatField()),
                ('platform_rating', models.FloatField()),
                ('course_difficulty', models.CharField(max_length=100)),
                ('what_do_you_like_most', models.TextField(blank=True, null=True)),
                ('what_do_you_like_least', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='course_gmt.coursetable')),
            ],
        ),
    ]
