# Generated by Django 5.1.7 on 2025-07-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0009_coursefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='content_quality_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='overall_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='platform_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='trainer_rating',
            field=models.IntegerField(),
        ),
    ]
