# Generated by Django 5.2.4 on 2025-08-07 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0010_alter_coursefeedback_content_quality_rating_and_more'),
        ('signup_gmt', '0032_remove_trainerdata_bank_name_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='project_pdfs/')),
                ('most_usage', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='course_gmt.coursetable')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='signup_gmt.trainerdata')),
            ],
        ),
    ]
