# Generated by Django 5.2.5 on 2025-09-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0012_project'),
        ('signup_gmt', '0032_remove_trainerdata_bank_name_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_submit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_file', models.FileField(upload_to='student_projects/files/')),
                ('project_document', models.FileField(upload_to='student_projects/documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to='course_gmt.projecttable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to='signup_gmt.studentinformation')),
            ],
            options={
                'unique_together': {('project', 'student')},
            },
        ),
    ]
