# Generated by Django 5.2.5 on 2025-09-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0013_project_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_submit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to='course_gmt.project'),
        ),
    ]
