# Generated by Django 5.2.5 on 2025-09-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0014_alter_project_submit_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTable',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('task_pdf', models.FileField(upload_to='course_tasks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='course_gmt.coursetable')),
            ],
        ),
    ]
