# Generated by Django 5.2.5 on 2025-09-23 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0015_tasktable'),
        ('signup_gmt', '0032_remove_trainerdata_bank_name_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='task_submissions/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to='signup_gmt.studentinformation')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='course_gmt.tasktable')),
            ],
            options={
                'unique_together': {('task', 'student')},
            },
        ),
    ]
