# Generated by Django 5.2.5 on 2025-09-29 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gmt', '0016_tasksubmit'),
        ('signup_gmt', '0032_remove_trainerdata_bank_name_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_gmt.coursetable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup_gmt.studentinformation')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
