# Generated by Django 5.2 on 2025-06-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup_gmt', '0029_alter_studentinformation_account_holder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('stipend', models.CharField(max_length=50)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('eligibility_criteria', models.TextField()),
                ('application_deadline', models.DateField()),
                ('number_of_openings', models.PositiveIntegerField()),
                ('contact_info', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('application_process', models.TextField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='signup_gmt.vendordata')),
            ],
        ),
    ]
