# Generated by Django 5.2 on 2025-06-05 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0029_alter_studentinformation_account_holder_name_and_more'),
        ('vendor_gmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField()),
                ('duration', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=255)),
                ('target_audience', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('registration_deadline', models.DateField()),
                ('registration_fee', models.CharField(max_length=50)),
                ('contact_information', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=255)),
                ('event_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='signup_gmt.vendordata')),
            ],
        ),
    ]
