# Generated by Django 5.2.5 on 2025-08-19 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0032_remove_trainerdata_bank_name_branch_and_more'),
        ('vendor_gmt', '0002_vendorevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSREvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Blood Donation', 'blood donation'), ('Green Based Events', 'green based events'), ('Motivational Talk', 'motivational talk'), ('Awarness', 'awarness'), ('other', 'Other')], max_length=50)),
                ('event_name', models.CharField(max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('agenda_file', models.FileField(blank=True, null=True, upload_to='csr_events/agenda/')),
                ('video', models.FileField(blank=True, null=True, upload_to='csr_events/videos/')),
                ('no_of_slots', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csrevents', to='signup_gmt.vendordata')),
            ],
        ),
    ]
