# Generated by Django 5.2.5 on 2025-08-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_gmt', '0003_csrevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csrevent',
            old_name='vendorid',
            new_name='vendor',
        ),
    ]
