# Generated by Django 5.2.5 on 2025-08-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_gmt', '0004_rename_vendorid_csrevent_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50)),
                ('role_name', models.CharField(default='requester', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('request_status', models.CharField(choices=[('open', 'Open'), ('Closed', 'closed')], default='pending', max_length=20)),
                ('blood_unit', models.IntegerField()),
                ('contact_no', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
