# Generated by Django 5.2.5 on 2025-08-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_gmt', '0005_bloodneed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodneed',
            name='request_status',
            field=models.CharField(choices=[('open', 'Open'), ('Closed', 'closed')], max_length=20),
        ),
    ]
