# Generated by Django 5.2 on 2025-05-22 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup_gmt.role')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('alt_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('skills', models.JSONField(blank=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('bank_location', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('institution_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('major_subject', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('total_score', models.FloatField(blank=True)),
                ('passedout', models.IntegerField(blank=True)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signup_gmt.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(default='trainer', max_length=20)),
                ('highest_qualification', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('total_experience_years', models.DecimalField(decimal_places=1, max_digits=4)),
                ('current_organization', models.CharField(blank=True, max_length=100)),
                ('previous_teaching_experience', models.TextField(blank=True)),
                ('certifications', models.CharField(blank=True, max_length=255)),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('bank_name_branch', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('resume', models.FileField(upload_to='uploads/resumes/')),
                ('id_proof', models.FileField(upload_to='uploads/id_proof/')),
                ('educational_certificates', models.FileField(upload_to='uploads/edu_certificates/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='uploads/profile_pics/')),
                ('available_days', models.CharField(max_length=100)),
                ('available_mode', models.CharField(max_length=50)),
                ('preferred_time_slots', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=10)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signup_gmt.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='VendorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_establishment', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('alternate_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('bank_name_branch', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='D:\x0bendor_files')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='D:\x0bendor_files')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='D:\x0bendor_files')),
                ('events_type', models.TextField(blank=True, null=True)),
                ('event_history', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=10)),
                ('role', models.CharField(default='vendor', max_length=20)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signup_gmt.logindetails')),
            ],
        ),
    ]
