# Generated by Django 5.2 on 2025-05-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdata',
            name='available_days',
            field=models.JSONField(blank=True),
        ),
    ]
