# Generated by Django 5.2 on 2025-05-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0002_alter_trainerdata_available_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='phone',
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
