# Generated by Django 5.2 on 2025-05-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0003_remove_studentinformation_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordata',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
