# Generated by Django 5.2 on 2025-05-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0004_vendordata_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerdata',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
