# Generated by Django 5.1.7 on 2025-05-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0005_trainerdata_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdata',
            name='educational_certificates',
            field=models.FileField(upload_to='pdfs'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='id_proof',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='resume',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
