# Generated by Django 5.2 on 2025-05-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0006_alter_trainerdata_educational_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdata',
            name='educational_certificates',
            field=models.FileField(upload_to='trainer/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='id_proof',
            field=models.FileField(upload_to='trainers/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainer/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='resume',
            field=models.FileField(upload_to='trainer/'),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='vendor'),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='vendor'),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='vendor'),
        ),
    ]
