# Generated by Django 5.2 on 2025-05-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0007_alter_trainerdata_educational_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student/'),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/'),
        ),
    ]
