# Generated by Django 5.2 on 2025-05-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0008_studentinformation_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
