# Generated by Django 5.2 on 2025-05-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0010_remove_studentinformation_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
