# Generated by Django 5.2 on 2025-05-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0011_studentinformation_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='contact_number',
        ),
    ]
