# Generated by Django 5.2 on 2025-05-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0012_remove_studentinformation_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
