# Generated by Django 5.2 on 2025-05-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0013_studentinformation_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='studentinformation',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='trainerdata',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='vendordata',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='cgpa',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='firstname',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='lastname',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='account_holder_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='account_number',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='address',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='alt_contact',
            field=models.CharField(default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='bank_location',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='bank_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='branch_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='contact_number',
            field=models.CharField(default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='date_of_birth',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='description',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='designation',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='father_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='firstname',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='gender',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='ifsc_code',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='institution_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='lastname',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='location',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='major_subject',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='mother_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='passedout',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='pincode',
            field=models.CharField(default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='profile_picture',
            field=models.ImageField(default=True, upload_to='student/'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='qualification',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='account_holder_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='account_number',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='available_days',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='available_mode',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='bank_name_branch',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='certifications',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='current_organization',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='date_of_birth',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='educational_certificates',
            field=models.FileField(default=True, upload_to='trainer/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='first_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='gender',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='highest_qualification',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='id_proof',
            field=models.FileField(default=True, upload_to='trainers/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='ifsc_code',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='last_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='phone_number',
            field=models.CharField(default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='preferred_time_slots',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='previous_teaching_experience',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='profile_picture',
            field=models.ImageField(default=True, upload_to='trainer/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='resume',
            field=models.FileField(default=True, upload_to='trainer/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='specialization',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='total_experience_years',
            field=models.DecimalField(decimal_places=1, default=True, max_digits=4),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='account_holder_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='account_number',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='address',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='alternate_contact',
            field=models.CharField(default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='bank_name_branch',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='business_license',
            field=models.FileField(default=True, upload_to='vendor'),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='business_name',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='business_type',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='contact_email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='contact_phone',
            field=models.CharField(default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='country',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='event_history',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='events_type',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='gst_certificate',
            field=models.FileField(default=True, upload_to='vendor'),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='gst_number',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='ifsc_code',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='pan_card',
            field=models.FileField(default=True, upload_to='vendor'),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='profile_picture',
            field=models.ImageField(default=True, upload_to='vendor/'),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='registration_number',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='year_of_establishment',
            field=models.IntegerField(default=True),
        ),
    ]
