# Generated by Django 5.2 on 2025-05-29 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0014_remove_studentinformation_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 5, 29)),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 5, 29)),
        ),
    ]
