# Generated by Django 5.2 on 2025-05-29 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0015_alter_studentinformation_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
