# Generated by Django 5.2 on 2025-05-29 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0016_alter_studentinformation_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
