# Generated by Django 5.2 on 2025-05-29 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0017_alter_studentinformation_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdata',
            name='account_holder_name',
            field=models.CharField(default='True', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
