# Generated by Django 5.2 on 2025-05-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0018_alter_trainerdata_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdata',
            name='account_holder_name',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
    ]
