# Generated by Django 5.2 on 2025-05-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0019_alter_trainerdata_account_holder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='skills',
            field=models.JSONField(default=list, null=True),
        ),
    ]
