# Generated by Django 5.2 on 2025-05-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0020_alter_studentinformation_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdata',
            name='available_days',
            field=models.JSONField(default=list, null=True),
        ),
    ]
