# Generated by Django 5.2 on 2025-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0021_alter_trainerdata_available_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='role',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='account_holder_name',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='account_number',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='address',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='alt_contact',
            field=models.CharField(default=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='bank_location',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='bank_name',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='branch_name',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='cgpa',
            field=models.FloatField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='contact_number',
            field=models.CharField(default=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='description',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='designation',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='email',
            field=models.EmailField(default=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='father_name',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='firstname',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='gender',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='ifsc_code',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='institution_name',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='lastname',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='location',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='major_subject',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='mother_name',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='passedout',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='pincode',
            field=models.CharField(default=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='profile_picture',
            field=models.ImageField(default=True, null=True, upload_to='student/'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='qualification',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='account_number',
            field=models.CharField(default=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='available_mode',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='bank_name_branch',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='certifications',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='current_organization',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='educational_certificates',
            field=models.FileField(default=True, null=True, upload_to='trainer/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='email',
            field=models.EmailField(default=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='first_name',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='gender',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='highest_qualification',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='id_proof',
            field=models.FileField(default=True, null=True, upload_to='trainers/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='ifsc_code',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='last_name',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='phone_number',
            field=models.CharField(default=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='preferred_time_slots',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='previous_teaching_experience',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='profile_picture',
            field=models.ImageField(default=True, null=True, upload_to='trainer/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='resume',
            field=models.FileField(default=True, null=True, upload_to='trainer/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='specialization',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='total_experience_years',
            field=models.DecimalField(decimal_places=1, default=True, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='account_holder_name',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='account_number',
            field=models.CharField(default=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='address',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='alternate_contact',
            field=models.CharField(default=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='bank_name_branch',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='business_license',
            field=models.FileField(default=True, null=True, upload_to='vendor'),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='business_name',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='business_type',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='contact_email',
            field=models.EmailField(default=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='contact_phone',
            field=models.CharField(default=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='country',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='event_history',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='events_type',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='firstname',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='gst_certificate',
            field=models.FileField(default=True, null=True, upload_to='vendor'),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='gst_number',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='ifsc_code',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='lastname',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='pan_card',
            field=models.FileField(default=True, null=True, upload_to='vendor'),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='profile_picture',
            field=models.ImageField(default=True, null=True, upload_to='vendor/'),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='registration_number',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='year_of_establishment',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
