# Generated by Django 5.2 on 2025-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0022_studentinformation_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerdata',
            name='address',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='pincode',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='pincode',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='pincode',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
    ]
