# Generated by Django 5.2 on 2025-05-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0023_trainerdata_address_trainerdata_pincode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='role',
        ),
    ]
