# Generated by Django 5.2 on 2025-05-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0024_remove_studentinformation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='role',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
