# Generated by Django 5.2 on 2025-05-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0025_studentinformation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdata',
            name='preferred_time_slots',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
