# Generated by Django 5.2 on 2025-05-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0027_alter_trainerdata_preferred_time_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdata',
            name='account_holder_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='available_days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='available_mode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='bank_name_branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='certifications',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='current_organization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='educational_certificates',
            field=models.FileField(blank=True, null=True, upload_to='trainer/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='highest_qualification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='trainers/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='preferred_time_slots',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='previous_teaching_experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainer/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='trainer/'),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='total_experience_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
