# Generated by Django 5.1.7 on 2025-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0029_alter_studentinformation_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerdata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendordata',
            name='address',
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='door_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='door_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='door_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
