# Generated by Django 5.1.7 on 2025-06-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0030_remove_trainerdata_address_remove_vendordata_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='address',
        ),
    ]
