# Generated by Django 5.2 on 2025-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_gmt', '0031_remove_studentinformation_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerdata',
            name='bank_name_branch',
        ),
        migrations.RemoveField(
            model_name='vendordata',
            name='bank_name_branch',
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='bank_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='branch_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='bank_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendordata',
            name='branch_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
