# Generated by Django 5.1.7 on 2025-07-28 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup_gmt', '0032_remove_trainerdata_bank_name_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('booking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='signup_gmt.studentinformation')),
            ],
        ),
    ]
