# Generated by Django 5.1.7 on 2025-07-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_gmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbooking',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='student_booking_pdfs/'),
        ),
        migrations.AddField(
            model_name='studentbooking',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
