# Generated by Django 5.2.4 on 2025-08-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gmt', '0001_initial'),
        ('signup_gmt', '0032_remove_trainerdata_bank_name_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_access_token', models.TextField(blank=True, null=True)),
                ('zoom_refresh_token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('management', 'Management')], max_length=50)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='portfolios/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=50, null=True)),
                ('zoom_start_url', models.URLField(blank=True, null=True)),
                ('zoom_join_url', models.URLField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_requests', to='signup_gmt.studentinformation')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_requests', to='signup_gmt.trainerdata')),
            ],
        ),
    ]
