# Generated by Django 5.2.4 on 2025-08-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gmt', '0002_trainerdata_interviewrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='interviewrequest',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='TrainerData',
        ),
        migrations.DeleteModel(
            name='InterviewRequest',
        ),
    ]
